### ISSUE TITLE
https error

### ISSUE THREAD

**Issue by fendermany** [criipto/verify-with-react-native-expo#1]
![Screenshot 2022-09-19 at 12 31 52](https://user-images.githubusercontent.com/71121334/190989397-ce41b6b5-8b26-411a-83f1-51df33dd051d.png)

Hi,
this code seems to work if dev tools are enabled, but without it, I get an error. Any thoughts on how to fix this?

**Comment by mickhansen** [comment]
@fendermany https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto needs to be available, which I believe it only is in localhost or https:// cases.

How are you loading the app in Expo?

**Comment by fendermany** [comment]
> @fendermany https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto needs to be available, which I believe it only is in localhost or https:// cases.
> 
> How are you loading the app in Expo?

I use development build, and I don't test it in production and I care about it

**Comment by mickhansen** [comment]
> > @fendermany https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto needs to be available, which I believe it only is in localhost or https:// cases.
> > How are you loading the app in Expo?
> 
> I use development build, and I don't test it in production and I care about it

I believe the Expo proxy supports HTTPs, can you try loading the app via that?

**Comment by fendermany** [comment]
> > > @fendermany https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto needs to be available, which I believe it only is in localhost or https:// cases.
> > > How are you loading the app in Expo?
> > 
> > 
> > I use development build, and I don't test it in production and I care about it
> 
> I believe the Expo proxy supports HTTPs, can you try loading the app via that?

How can I use expo with proxy?

**Comment by mickhansen** [comment]
@fendermany How are you launching expo and your app currently? What platform, what method (tunnel, lan, etc?)?

**Comment by mickhansen** [comment]
Latest commit may also have helped as that moved to `expo-crypto`

**Comment by fendermany** [comment]
> @fendermany How are you launching expo and your app currently? What platform, what method (tunnel, lan, etc?)?

I use `npx expo start --dev-client` and after start development build.

I tried expo-crypto. It is works! Thank you

**Comment by mickhansen** [comment]
@fendermany Great!
